### ISSUE TITLE
[FEAT] 3차 세미나 실습 과제

### ISSUE THREAD

**Issue by geniusYoo** [NOW-SOPT-SERVER/YoungjaeYou#7]
## 구현 내용

- [x] 블로그 글 작성 POST API
- [x] 블로그 글 검색 GET API
- [x] SuccessStatusResponse, ErrorReponse 적절히 변경해 GET API Response로
- [x] 블로그를 소유하지 않은 사용자가 해당 블로그에 글을 작성할 경우 발생할 예외 처리 

## Task

- [x] Specification 도입해보기 (게시물 공개 범위에 따른 검색 조건)
- [x] Post Controller / Service / Repository Layer 적절히 구성
- [x] Exception에 대해 심도 있게 고민해보기
